/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package part_b;

import java.util.ArrayList;
import java.util.List;

import org.joda.time.*;

import part_a.*;
import part_a.Module;

public class App {

    public App() {

        List<Student> students = new ArrayList<Student>();
        List<CourseProgramme> courses = new ArrayList<CourseProgramme>();

        students.add(new Student("Mark", 21, "11/09/2001", 19459946));

        students.add(new Student("Joe", 23, "5/10/1999", 50901708));
        students.add(new Student("Mary", 22, "29/2/2000", 36705652));

        
        Lecturer Schukat = new Lecturer("Michael Schukat", 1, "29/09/2022", "IT402");
        Lecturer Corcoran = new Lecturer("Peter Corcoran", 0, "13/10/2022", "EE347");
        Lecturer Morgan = new Lecturer("Fearghal Morgan", 1, "13/10/2022", "EE451");

        Module Embedded_Systems = new Module("Embedded Systems Applications Programming", "EE347", Corcoran);
        Module System_on_chip = new Module("System on Chip Design 1", "EE451", Morgan);
        Module SoftwareEngineering_III = new Module("Software engineering III", "CT417", Schukat);
        
        
        courses.add(new CourseProgramme("ECE", DateTime.parse("2022-09-5T11:00"), DateTime.parse("2022-03-31T15:00")));
        
        for (int i = 0; i < students.size(); i++) {
            students.get(i).addCourses(courses.get(0));
            students.get(i).addModules(SoftwareEngineering_III);
            students.get(i).addModules(Embedded_Systems);
            students.get(i).addModules(System_on_chip);
            courses.get(0).addStudents(students.get(i));
            SoftwareEngineering_III.addStudents(students.get(i));
            Embedded_Systems.addStudents(students.get(i));
            System_on_chip.addStudents(students.get(i));            
        }
        
        courses.get(0).addModules(SoftwareEngineering_III);
        courses.get(0).addModules(Embedded_Systems);
        courses.get(0).addModules(System_on_chip);

        for (int i = 0; i < courses.size(); i++) {
            System.out.println(courses.get(i));
        }

    }
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App app = new App();
    }
}
